version: "3.8"

services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo-express
      - mongo
    volumes:
      - /node_modules
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8085:8085"